modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/MOAKIEE/AE2LT-Packaged-Pattern-Provider/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "icon.png"
logoBlur = false
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "ae2"
type = "required"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "ae2lt"
type = "required"
versionRange = "${ae2lt_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "thunderbolt"
type = "required"
versionRange = "${thunderbolt_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "ars_nouveau"
type = "optional"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "draconicevolution"
type = "optional"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "actuallyadditions"
type = "optional"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "extendedcrafting"
type = "optional"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "avaritia"
type = "optional"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "mysticalagriculture"
type = "optional"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "occultism"
type = "optional"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "mekmm"
type = "optional"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "malum"
type = "optional"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "botania"
type = "optional"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
